### ISSUE TITLE
Logout user on clicking logout button

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork-mobile#13]
When logout button in side drawer is clicked removed the `access_token` and load login page

**Comment by roh8raut** [comment]
Hi is anyone working on this issue?

**Comment by Hasnayeen** [comment]
nope, you can take this

**Comment by payam-zahedi** [comment]
Hi @Hasnayeen, is this issue assigned? I would like to work on it.

**Comment by Hasnayeen** [comment]
Sure, go ahead. But if you decide not to do this later on please mention on the issue so that other can pick it up.

**Comment by payam-zahedi** [comment]
@Hasnayeen for deleting `access_token ` I think, I have to use FlutterSecureStorage and delete access token in side_menu.dart file. but can you explain how can I navigate to Login Page?
Should I use Navigator or BLoc pattern or anything else?
and if it's possible plz assign this issue to me.
Thanks.

**Comment by Hasnayeen** [comment]
create a logged out event in auth_event and in auth_bloc yield initial auth state in response, and dispatch the event from button on press

**Comment by payam-zahedi** [comment]
dear @Hasnayeen I have written the code. but when I run the app and test the solution I got User not found error. please help me to fill the below sections.

- Web app URL
- E-mail
- Password

Thanks.

**Comment by Hasnayeen** [comment]
@payam-zahedi use below credentials
web url: `https://www.goodworkfor.life` (don't add slash at the end)
e-mail: `guest@example.com`
password: `guestpass`

**Comment by payam-zahedi** [comment]
Dear @Hasnayeen , I've sent a PR for this issue. please check it out and tell me if any changes needed.

**Comment by Hasnayeen** [comment]
Please don't remove the pr template in the pr and go through the checklist to make sure the pr is appropriate. Check this pr #12  as a sample

**Comment by payam-zahedi** [comment]
@Hasnayeen, you can check it now.
