### ISSUE TITLE
Add network connectivity check

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork-mobile#4]
Check whether there is available network connection when the app open before showing login screen.

**Comment by CheshtaK** [comment]
How are we supposed to go about this issue? Should we just display a toast saying "No network connection" when the app opens?

**Comment by Hasnayeen** [comment]
@CheshtaK yes a toast or alert dialog saying "No network available, please turn on your wifi or cellular network".

**Comment by CheshtaK** [comment]
Great! I'll open a PR soon.

**Comment by CheshtaK** [comment]
I'm facing the following error while executing "flutter get packages". Should I use 'dependency_overrides' for meta:^1.1.7 temporarily? It seems to solve the error.

![error](https://user-images.githubusercontent.com/32400008/66151809-af499100-e635-11e9-9f16-7e6792358912.jpg)

**Comment by Hasnayeen** [comment]
yes
