### ISSUE TITLE
Show error message on unsuccessful login

### ISSUE THREAD

**Issue by Hasnayeen** [iluminar/goodwork-mobile#9]
show error message in a alert dialog when login attempt is unsuccessful and when pressed on 'ok' button show login screen

**Comment by Kartik-Sama** [comment]
If it is to be done with javascript, can I take up this issue?

**Comment by AlaaEdAouimeur** [comment]
How do you want the error to be shown? In a form of. A toast?

**Comment by Hasnayeen** [comment]
An alert dialog with 'ok' button

**Comment by JaredEzz** [comment]
I can do this one in dart 🖐️

**Comment by Hasnayeen** [comment]
@JaredEzz  Sure, go ahead.

**Comment by AbhishekDoshi26** [comment]
Can i take up?

**Comment by Hasnayeen** [comment]
Sorry its already implemented, I forgot to close the issue
